### ISSUE TITLE
Observable spy is always undefined

### ISSUE THREAD

**Issue by WESquad-spires** [hirezio/auto-spies#44]
**Describe the bug**
A service with a method returning an Observable is always 'undefined' when testing it with jest-auto-spies (same test passes with a jasmine-auto-spies configuration).

**To Reproduce**

1. Create an Injectable service (let's say DummyService) with a method returning an Observable
2. Inject this service in AppComponent and consume the service method by subscribing to its result
3. Test AppComponent (providing an AutoSpy for DummyService) only checking that componentUnderTest is truthy
4. Two errors are raised `An error was thrown in Given():  Cannot read property 'subscribe' of undefined` and `An error was thrown in Then():  expect(received).toBeTruthy() Received: undefined`

**Expected behavior**
DummyService is injected in TestBed thus having a value and the test passes

**Additional context**

***DummyService***
```ts
import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { delay, map } from 'rxjs/operators';

@Injectable({
  providedIn: 'root'
})
export class DummyService {

  getDummyData(): Observable<{ id: number, label: string }[]> {
    return of(null).pipe(delay(500)).pipe(map(() => {
      return [
        { id: 1, label: 'some data' },
        { id: 2, label: 'some other data' }
      ];
    }));
  }
}
```

***AppComponent***
```ts
import { Component } from '@angular/core';
import { DummyService } from './services/dummy.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  dummyData: any;

  constructor(
    private dummyService: DummyService
  ) {
    this.initDummyData();
  }

  private initDummyData(): void {
    this.dummyService.getDummyData().subscribe(res => {
      this.dummyData = res;
    });
  }
}
```

***AppComponent spec***
```ts
import { TestBed } from '@angular/core/testing';
import { provideAutoSpy, Spy } from 'jest-auto-spies';
import { AppComponent } from './app.component';
import { DummyService } from './services/dummy.service';

describe(`AppComponent`, () => {
  let componentUnderTest: AppComponent;
  let dummyServiceSpy: Spy<DummyService>;

  Given(() => {
    TestBed.configureTestingModule({
      providers: [
        AppComponent,
        provideAutoSpy(DummyService)
      ]
    });

    componentUnderTest = TestBed.inject(AppComponent);
    dummyServiceSpy = TestBed.inject<any>(DummyService);
  });

  describe('EVENT: init', () => {
    Then(() => {
      expect(componentUnderTest).toBeTruthy();
    });
  });
});
```

***Result Error***
```
 PASS  src/app/services/dummy.service.spec.ts
 FAIL  src/app/app.component.spec.ts
  ● AppComponent › EVENT: init › 

    An error was thrown in Given(): 
      TypeError: Cannot read property 'subscribe' of undefined

      19 |
      20 |   private initDummyData(): void {
    > 21 |     this.dummyService.getDummyData().subscribe(res => {
         |     ^
      22 |       this.dummyData = res;
      23 |     });
      24 |   }

      at AppComponent.initDummyData (src/app/app.component.ts:21:5)
      at new AppComponent (src/app/app.component.ts:17:10)
      at Object.AppComponent_Factory [as factory] (ng:/AppComponent/ɵfac.js:5:10)
      at R3Injector.Object.<anonymous>.R3Injector.hydrate (../packages/core/src/di/r3_injector.ts:412:29)
      at R3Injector.Object.<anonymous>.R3Injector.get (../packages/core/src/di/r3_injector.ts:209:23)
      at NgModuleRef$1.Object.<anonymous>.NgModuleRef$1.get (../packages/core/src/render3/ng_module_ref.ts:76:29)
      at TestBedRender3.Object.<anonymous>.TestBedRender3.inject (../packages/core/testing/src/r3_test_bed.ts:278:48)
      at Function.Object.<anonymous>.TestBedRender3.inject (../packages/core/testing/src/r3_test_bed.ts:167:33)
      at Given (src/app/app.component.spec.ts:18:34)

  ● AppComponent › EVENT: init › 

    An error was thrown in Then(): 
      Error: expect(received).toBeTruthy()

    Received: undefined

      22 |   describe('EVENT: init', () => {
      23 |     Then(() => {
    > 24 |       expect(componentUnderTest).toBeTruthy();
         |                                  ^
      25 |     });
      26 |   });
      27 |

      at Then (src/app/app.component.spec.ts:24:34)
```

**Comment by shairez** [comment]
Hi, sorry for the late reply, just cleaning up issues now.

The default behavior of `createSpyFromClass` or `provideAutoSpy` is to just create a fake object with methods that "have the potential" of returning an observable. 

In order for the methods to return anything, they need to be configured **before** you call subscribe on their return values.

That means that you need to called `nextWith` or even `returnSubject` before you run the `inject()` of the component (`inject` calls the constructor which in turn calls `subscribe`).

So I suggest to move your `inject(component)` to the `When` function after you configured your observable spy in the `Given`
