### ISSUE TITLE
Spying on Subject example in documentation service can't be imported

### ISSUE THREAD

**Issue by hokrc01** [hirezio/auto-spies#48]
I am using jasmine-auto-spies v 6.9.x

I wrote a simple service
```
import { Injectable } from '@angular/core';
import { Subject } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class SecurityService {
  codeChange: Subject<number> = new Subject<number>();
  constructor() { }
}
```

Then I created a Test for a component that consumes the service:  This creates the following error 

> TypeError: Cannot read property 'subscribe' of undefined
          at OverlayComponent.initSecurityCodeChange (projects/my/src/app/security/overlay/overlay.component.ts:21:8)
          at OverlayComponent.ngOnInit (projects/my/src/app/security/overlay/overlay.component.ts:16:10)
          at callHook (node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:2486:1)
          at callHooks (node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:2457:1)
          at executeInitAndCheckHooks (node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:2408:1)
          at refreshView (node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:9207:1)
          at renderComponentOrTemplate (node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:9306:1)
          at tickRootContext (node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:10532:1)
          at detectChangesInRootView (node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:10557:1)
          at RootViewRef.detectChanges (node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:22569:1)

The test is as follows:

```
  let securitySpy: Spy<SecurityService>;
  Given(() => {
    securitySpy = createSpyFromClass(SecurityService, {
      observablePropsToSpyOn: ['codeChange']
    });
    component = new OverlayComponent(securitySpy);
  });
  describe('METHOD:  ngOnInit()', () => {
    Given(() => {
      component.ngOnInit();
    });
    When(() => {
      securitySpy.codeChange.nextWith(5);
    });
    Then(() => {
      expect(component.componentCode).toEqual(5)
    });
  });
});

@Injectable({
  providedIn: 'root'
})
class SecurityService {
  codeChange = new Subject<number>();
}

```
When I move the service code to the test file the test passes.  any thoughts?

**Comment by shairez** [comment]
Hi @hokrc01 

that's weird. 

The problem doesn't seem to come from the library... I just added a test that proves that spying on subjects work as well.  

Can you please share your component's code? and your spec imports?

**Comment by shairez** [comment]
closing this in the meantime, when you'll have time please add the component code so we could further check it out
