### ISSUE TITLE
Angular 13 Breaks createSpyFromClass and ProvideAutoSpy

### ISSUE THREAD

**Issue by hokrc01** [hirezio/auto-spies#55]
**Describe the bug**
Added        { provide: C247HttpClientService, useValue: createSpyFromClass(C247HttpClientService)} then replaced with 
provideAutoSpiy(C247HttpClientService).  ran ng test at got the error 

```
Chrome 96.0.4664.110 (Linux x86_64) ERROR
  An error was thrown in afterAll
  Uncaught ReferenceError: global is not defined
  ReferenceError: global is not defined
      at Object.1186 (http://localhost:9876/_karma_webpack_/webpack:/node_modules/randombytes/browser.js:16:1)
      at require (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Object.7172 (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@hirez_io/auto-spies-core/node_modules/serialize-javascript/index.js:9:19)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Object.5260 (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@hirez_io/auto-spies-core/dist/errors/error-handler.js:5:17)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Object.7346 (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@hirez_io/auto-spies-core/dist/create-function-auto-spy.js:5:23)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Object.7841 (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@hirez_io/auto-spies-core/dist/index.js:13:14)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)

The actual Test Code is as follows:

import { TestBed } from '@angular/core/testing';
import { C247HttpClientService } from '@c247-common/c247-http-client';
import { createSpyFromClass } from 'jasmine-auto-spies';

import { SelectTournamentService } from './select-tournament.service';

describe('SelectTournamentService', () => {
  let service: SelectTournamentService;

  beforeEach(() => {
    TestBed.configureTestingModule({      
     providers:[
       SelectTournamentService,
       { provide: C247HttpClientService, useValue: createSpyFromClass(C247HttpClientService)}

      ]
    });
    service = TestBed.inject<any>(SelectTournamentService);
  });

  it('should be created', () => {
     expect(service).toBeTruthy();
  });
});

**Comment by shairez** [comment]
Thanks for the report

Just issued a PR that should fix this

**Comment by hokrc01** [comment]
This problem seems to be fixed.  Thank you
